#!/usr/bin/env bash

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

set -e

cd "$(dirname "$0")/.."

if [ "$U2F_ENABLED" = 1 ]; then
    vendor/trezor-common/tools/cointool.py render firmware/fido2
fi

if [ "$EMULATOR" = 1 ]; then
    make -C emulator
else
    make -C vendor/libopencm3 lib/gd32/f4xx
fi
make -C vendor/libsol

rm -rf *.d *.o

make

if [ "$EMULATOR" != 1 ]; then
    rm bootloader/*.bin || true
    make -C bootloader
fi

rm  -rf *.d *.o

# invoking nanopb_generator to make sure its proto files are generated
nanopb_generator >/dev/null || true
make -C firmware/protob
make -C firmware

if [ "$EMULATOR" != 1 ]; then
    make -C firmware sign
    # make -C intermediate_fw
    # make -C intermediate_fw sign
fi
